/**
 * GLSL sources for Grainfall WebGL2 renderer.
 * Plain script — attaches window.GrainfallShaders.
 */
(function (root) {
  "use strict";

  // Clip-space quad. Flip V so uv (0,0) is top-left — matches sim grid /
  // Canvas2D / ImageData (y grows downward). Without this, materials render
  // upside-down relative to the overlay cursor and paint mapping.
  var VERT = [
    "#version 300 es",
    "in vec2 aPos;",
    "out vec2 vUv;",
    "void main(){",
    "  vUv = vec2(aPos.x * 0.5 + 0.5, 0.5 - aPos.y * 0.5);",
    "  gl_Position = vec4(aPos, 0.0, 1.0);",
    "}",
  ].join("\n");

  // Shared helpers inlined into material / light passes.
  var COMMON = [
    "precision highp float;",
    "precision highp int;",
    "in vec2 vUv;",
    "uniform sampler2D uGrid;",
    "uniform sampler2D uLife;",
    "uniform sampler2D uNoise;",
    "uniform sampler2D uPalette;",
    "uniform sampler2D uProps;",
    "uniform sampler2D uExtras;",
    "uniform vec2 uTexel;",
    "uniform float uFrame;",
    "uniform float uReducedMotion;",
    "",
    "const float MAT_EMPTY = 0.0;",
    "const float MAT_WALL = 1.0;",
    "const float MAT_SAND = 2.0;",
    "const float MAT_WATER = 3.0;",
    "const float MAT_OIL = 4.0;",
    "const float MAT_PLANT = 5.0;",
    "const float MAT_FIRE = 6.0;",
    "const float MAT_LAVA = 7.0;",
    "const float MAT_STEAM = 8.0;",
    "const float MAT_NAPALM = 9.0;",
    "const float MAT_STONE = 10.0;",
    "const float MAT_GUNPOWDER = 11.0;",
    "const float MAT_ICE = 12.0;",
    "const float MAT_SNOW = 13.0;",
    "const float MAT_ACID = 14.0;",
    "const float MAT_WOOD = 15.0;",
    "const float MAT_SEED = 16.0;",
    "const float MAT_GAS = 17.0;",
    "const float MAT_GLASS = 18.0;",
    "const float MAT_MERCURY = 19.0;",
    "const float MAT_CLONE = 20.0;",
    "const float MAT_TORCH = 21.0;",
    "const float MAT_NITRO = 22.0;",
    "const float MAT_VIRUS = 23.0;",
    "const float MAT_FAN = 24.0;",
    "const float MAT_ANT = 25.0;",
    "const float MAT_BIRD = 26.0;",
    "const float MAT_FIGHTER = 27.0;",
    "const float MAT_METAL = 28.0;",
    "const float MAT_LIGHTNING = 29.0;",
    "",
    "float matAt(vec2 uv){ return floor(texture(uGrid, uv).r * 255.0 + 0.5); }",
    "float lifeAt(vec2 uv){ return floor(texture(uLife, uv).r * 255.0 + 0.5); }",
    "float noiseAt(vec2 uv){ return floor(texture(uNoise, uv).r * 255.0 + 0.5); }",
    "vec4 pal(float m){ return texture(uPalette, vec2((m + 0.5) / 256.0, 0.5)); }",
    "vec4 props(float m){ return texture(uProps, vec2((m + 0.5) / 256.0, 0.5)); }",
    "vec4 extras(float m){ return texture(uExtras, vec2((m + 0.5) / 256.0, 0.5)); }",
    "float heightOf(float m){ return props(m).r; }",
    "float animFrame(){ return uReducedMotion > 0.5 ? 0.0 : uFrame; }",
    "float triWave(float x){ float t = mod(x, 64.0); return t > 31.0 ? 63.0 - t : t; }",
    "vec3 clamp255(vec3 c){ return clamp(c, 0.0, 255.0); }",
  ].join("\n");

  var CELL_FRAG = [
    "#version 300 es",
    COMMON,
    "layout(location=0) out vec4 oColor;",
    "layout(location=1) out vec4 oEmissive;",
    "layout(location=2) out vec4 oThermal;",
    "",
    "vec3 shadeMaterial(float m, float lf, float n0, float frame){",
    "  vec3 base = pal(m).rgb * 255.0;",
    "  vec3 rgb = base;",
    "  if (m == MAT_EMPTY){",
    "    float eg = mod(n0, 8.0) - 3.0;",
    "    rgb = clamp255(base + vec3(eg, eg, eg + step(4.0, mod(n0, 8.0))));",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_FIRE){",
    "    float fl = mod(n0 + frame * 11.0, 32.0);",
    "    rgb = vec3(255.0, min(255.0, 60.0 + lf * 3.0 + fl), max(0.0, lf * 2.0 - 40.0 + fl * 0.5));",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_LAVA){",
    "    float p = triWave(n0 + frame);",
    "    rgb = vec3(min(255.0, 205.0 + p + mod(n0, 16.0)), 40.0 + p + mod(n0, 8.0), 14.0);",
    "    if (mod(n0 + frame * 3.0, 64.0) < 2.0) rgb = vec3(255.0, min(255.0, 180.0 + mod(n0, 32.0)), 40.0);",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_NAPALM){",
    "    float np = triWave(n0 * 3.0 + frame * 4.0) * 0.5;",
    "    rgb = vec3(255.0, 28.0 + np * 3.0, 18.0 + np);",
    "    if (mod(n0, 16.0) < 2.0) rgb.g = min(255.0, 120.0 + np * 4.0);",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_WATER){",
    "    if (lf > 0.5){",
    "      bool head = lf > 1.5;",
    "      rgb = head ? vec3(200.0, 245.0, 255.0) : vec3(120.0, 210.0, 255.0);",
    "    } else {",
    "      float wv = triWave(n0 * 3.0 + frame * 2.0) * 0.5;",
    "      float dv = mod(n0, 20.0) - 10.0 + wv - 8.0;",
    "      rgb = clamp255(base + vec3(dv * 0.5, dv, dv));",
    "    }",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_OIL){",
    "    float ov = mod(n0, 16.0) - 8.0;",
    "    rgb = clamp255(vec3(88.0 + ov, 62.0 + ov, 36.0 + ov * 0.5));",
    "    if (mod(n0 + frame, 64.0) < 3.0) rgb = min(vec3(255.0), rgb + vec3(50.0, 30.0, 70.0));",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_METAL || (m == MAT_MERCURY && lf > 0.5)){",
    "    if (lf > 0.5){",
    "      bool head = lf > 1.5;",
    "      rgb = head ? vec3(235.0, 250.0, 255.0) : vec3(120.0, 220.0, 255.0);",
    "    } else {",
    "      float mv = mod(n0, 18.0) - 9.0;",
    "      rgb = clamp255(base + vec3(mv));",
    "    }",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_MERCURY){",
    "    float mp = triWave(n0 + frame * 2.0) * 0.5;",
    "    rgb = vec3(165.0 + mp * 2.0, 168.0 + mp * 2.0, 175.0 + mp * 2.0);",
    "    if (mod(n0, 32.0) < 2.0) rgb = vec3(230.0);",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_LIGHTNING){",
    "    float tf = mod(n0 + frame * 7.0, 32.0);",
    "    rgb = vec3(255.0, min(255.0, 210.0 + tf), 40.0 + tf * 0.5);",
    "    if (mod(frame + n0, 4.0) < 2.0) rgb = vec3(255.0);",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_STEAM){",
    "    float k = 0.25 + min(0.55, lf / 140.0);",
    "    rgb = vec3(12.0 + 168.0 * k, 14.0 + 176.0 * k, 20.0 + 190.0 * k);",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_ACID){",
    "    float ap = triWave(n0 * 5.0 + frame * 3.0) * 0.5;",
    "    rgb = vec3(130.0 + ap * 3.0, min(255.0, 225.0 + ap), 40.0 + ap);",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_GAS){",
    "    float gp = triWave(n0 * 3.0 + frame) * 0.5;",
    "    rgb = vec3(145.0 + gp, 150.0 + gp, 70.0 + gp * 0.5);",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_ICE){",
    "    float iv = mod(n0, 20.0) - 10.0;",
    "    rgb = clamp255(vec3(145.0 + iv, 205.0 + iv, 255.0));",
    "    if (mod(n0 * 3.0 + frame * 2.0, 64.0) < 3.0) rgb = vec3(230.0, 245.0, 255.0);",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_SNOW){",
    "    float sv = mod(n0, 14.0) - 7.0;",
    "    rgb = clamp255(vec3(230.0 + sv, 235.0 + sv, 245.0 + sv));",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_PLANT){",
    "    float pv = mod(n0, 36.0) - 18.0;",
    "    rgb = clamp255(vec3(48.0 + pv, 155.0 + pv, 58.0 + pv * 0.5));",
    "    if (mod(n0, 16.0) < 0.5) rgb -= vec3(20.0, 30.0, 0.0);",
    "    return clamp(rgb, 0.0, 255.0) / 255.0;",
    "  }",
    "  if (m == MAT_VIRUS){",
    "    float vp = triWave(n0 + frame * 5.0) * 0.5;",
    "    rgb = vec3(min(255.0, 180.0 + vp * 3.0), 40.0 + vp, min(255.0, 190.0 + vp * 2.0));",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_CLONE){",
    "    float cp = triWave(n0 + frame * 2.0) * 0.5;",
    "    float learned = lf > 0.5 ? 1.0 : 0.0;",
    "    rgb = vec3(160.0 + cp + learned * 30.0, 155.0 + cp + learned * 25.0, 40.0 + cp * 0.5);",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_TORCH){",
    "    float tp = triWave(n0 + frame * 9.0) * 0.5;",
    "    rgb = vec3(220.0 + tp * 0.5, 90.0 + tp * 2.0, 30.0 + tp);",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_NITRO){",
    "    float ntp = triWave(n0 + frame * 6.0) * 0.5;",
    "    rgb = vec3(200.0 + ntp, 200.0 + ntp, 40.0 + ntp);",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_GLASS){",
    "    float gv = mod(n0, 16.0) - 8.0;",
    "    rgb = clamp255(vec3(175.0 + gv, 200.0 + gv, 215.0 + gv));",
    "    if (mod(n0, 32.0) < 2.0) rgb = vec3(245.0);",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_WOOD){",
    "    float wd = mod(n0, 34.0) - 17.0;",
    "    rgb = clamp255(vec3(120.0 + wd, 80.0 + wd, 42.0 + wd * 0.5));",
    "    if (mod(n0, 8.0) < 0.5) rgb -= vec3(25.0, 18.0, 0.0);",
    "    return clamp(rgb, 0.0, 255.0) / 255.0;",
    "  }",
    "  if (m == MAT_GUNPOWDER){",
    "    float gu = mod(n0, 28.0) - 14.0;",
    "    rgb = clamp255(vec3(62.0 + gu, 62.0 + gu, 68.0 + gu));",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_SAND){",
    "    float sdv = mod(n0, 40.0) - 20.0;",
    "    rgb = clamp255(vec3(230.0 + sdv, 196.0 + sdv, 92.0 + sdv * 0.5));",
    "    if (mod(n0 + floor(frame * 0.25), 64.0) < 2.0) rgb = min(vec3(255.0), rgb + vec3(25.0, 20.0, 10.0));",
    "    return rgb / 255.0;",
    "  }",
    "  if (m == MAT_STONE){",
    "    float sk = mod(n0, 26.0) - 13.0;",
    "    rgb = clamp255(vec3(118.0 + sk, 116.0 + sk, 110.0 + sk));",
    "    if (mod(n0, 16.0) < 0.5) rgb -= vec3(18.0, 16.0, 14.0);",
    "    return clamp(rgb, 0.0, 255.0) / 255.0;",
    "  }",
    "  if (m == MAT_WALL){",
    "    float wv = mod(n0, 16.0) - 8.0;",
    "    rgb = clamp255(base + vec3(wv));",
    "    return rgb / 255.0;",
    "  }",
    "  // Fan / creatures / seed: directional cue via life",
    "  if (m == MAT_FAN || m == MAT_ANT || m == MAT_BIRD || m == MAT_FIGHTER || m == MAT_SEED){",
    "    float vr = 16.0;",
    "    float v = mod(n0, vr) - vr * 0.5;",
    "    rgb = clamp255(base + vec3(v));",
    "    // Mild highlight for facing (life 1..8)",
    "    if (lf > 0.5){",
    "      float pulse = 0.08 + 0.04 * sin((frame + n0) * 0.2);",
    "      rgb = min(vec3(255.0), rgb + vec3(pulse * 40.0));",
    "    }",
    "    return rgb / 255.0;",
    "  }",
    "  float vr2 = 20.0;",
    "  float v2 = mod(n0, vr2) - vr2 * 0.5;",
    "  rgb = clamp255(base + vec3(v2));",
    "  return rgb / 255.0;",
    "}",
    "",
    "void main(){",
    "  float m = matAt(vUv);",
    "  float lf = lifeAt(vUv);",
    "  float n0 = noiseAt(vUv);",
    "  float frame = animFrame();",
    "  vec3 color = shadeMaterial(m, lf, n0, frame);",
    "",
    "  // Soft liquid surface highlight when air above",
    "  float above = matAt(vUv - vec2(0.0, uTexel.y));",
    "  vec4 fl = props(m);",
    "  float flags = fl.a * 255.0;",
    "  bool liquid = mod(floor(flags / 2.0), 2.0) > 0.5;",
    "  if (liquid && above < 0.5){",
    "    color = min(vec3(1.0), color + vec3(0.12, 0.14, 0.16));",
    "  }",
    "",
    "  // Glass / steam translucency tint toward empty background",
    "  float opacity = extras(m).r;",
    "  if (opacity < 0.98 && m > 0.5){",
    "    vec3 bg = shadeMaterial(0.0, 0.0, n0, frame);",
    "    color = mix(bg, color, clamp(opacity + 0.15, 0.0, 1.0));",
    "  }",
    "",
    "  // Emissive strength",
    "  float em = pal(m).a;",
    "  if (m == MAT_FIRE) em = clamp(0.55 + lf / 180.0, 0.0, 1.0);",
    "  else if (m == MAT_LAVA) em = 0.75;",
    "  else if (m == MAT_LIGHTNING) em = 1.0;",
    "  else if (m == MAT_TORCH) em = 0.8;",
    "  else if ((m == MAT_METAL || m == MAT_WATER || m == MAT_MERCURY) && lf > 0.5) em = lf > 1.5 ? 0.95 : 0.55;",
    "  else if (m == MAT_NAPALM) em = 0.65;",
    "  else if (m == MAT_NITRO) em = 0.35 + 0.15 * sin(frame * 0.3 + n0);",
    "  else if (m == MAT_ACID) em = 0.25;",
    "",
    "  float thermal = extras(m).g;",
    "  if (m == MAT_FIRE) thermal = clamp(lf / 140.0, 0.3, 1.0);",
    "  if ((m == MAT_METAL || m == MAT_WATER) && lf > 0.5) thermal = max(thermal, 0.45);",
    "",
    "  oColor = vec4(color, 1.0);",
    "  oEmissive = vec4(color * em, em);",
    "  oThermal = vec4(thermal, em, 0.0, 1.0);",
    "}",
  ].join("\n");

  var LIGHT_FRAG = [
    "#version 300 es",
    COMMON,
    "uniform sampler2D uScene;",
    "uniform sampler2D uEmissive;",
    "layout(location=0) out vec4 oColor;",
    "layout(location=1) out vec4 oEmissive;",
    "",
    "void main(){",
    "  vec3 albedo = texture(uScene, vUv).rgb;",
    "  vec4 emis = texture(uEmissive, vUv);",
    "  float m = matAt(vUv);",
    "  // No AO / contact / directional shadows — they muddy the pixel look.",
    "  // Keep only a faint specular glint on shiny materials.",
    "  vec3 color = albedo;",
    "  if (m > 0.5){",
    "    float hL = heightOf(matAt(vUv - vec2(uTexel.x, 0.0)));",
    "    float hR = heightOf(matAt(vUv + vec2(uTexel.x, 0.0)));",
    "    float hU = heightOf(matAt(vUv - vec2(0.0, uTexel.y)));",
    "    float hD = heightOf(matAt(vUv + vec2(0.0, uTexel.y)));",
    "    vec3 nrm = normalize(vec3(hL - hR, hU - hD, 0.7));",
    "    vec3 L = normalize(vec3(-0.35, -0.55, 0.75));",
    "    float rough = props(m).g;",
    "    float specStr = props(m).b;",
    "    vec3 H = normalize(L + vec3(0.0, 0.0, 1.0));",
    "    float spec = pow(clamp(dot(nrm, H), 0.0, 1.0), mix(40.0, 10.0, rough)) * specStr;",
    "    color = min(vec3(1.0), albedo + vec3(spec * 0.12));",
    "  }",
    "  oColor = vec4(color, 1.0);",
    "  oEmissive = emis;",
    "}",
  ].join("\n");

  var BLOOM_THRESH_FRAG = [
    "#version 300 es",
    "precision highp float;",
    "in vec2 vUv;",
    "uniform sampler2D uEmissive;",
    "uniform float uThreshold;",
    "out vec4 oColor;",
    "void main(){",
    "  vec4 e = texture(uEmissive, vUv);",
    "  float b = max(e.r, max(e.g, e.b)) * e.a;",
    "  float t = max(0.0, b - uThreshold);",
    "  oColor = vec4(e.rgb * t * 1.6, 1.0);",
    "}",
  ].join("\n");

  var BLOOM_BLUR_FRAG = [
    "#version 300 es",
    "precision highp float;",
    "in vec2 vUv;",
    "uniform sampler2D uTex;",
    "uniform vec2 uDirection;",
    "uniform vec2 uTexel;",
    "out vec4 oColor;",
    "void main(){",
    "  vec2 d = uDirection * uTexel;",
    "  vec3 c = texture(uTex, vUv).rgb * 0.227027;",
    "  c += texture(uTex, vUv + d * 1.384615).rgb * 0.316216;",
    "  c += texture(uTex, vUv - d * 1.384615).rgb * 0.316216;",
    "  c += texture(uTex, vUv + d * 3.230769).rgb * 0.070270;",
    "  c += texture(uTex, vUv - d * 3.230769).rgb * 0.070270;",
    "  oColor = vec4(c, 1.0);",
    "}",
  ].join("\n");

  var THERMAL_FRAG = [
    "#version 300 es",
    "precision highp float;",
    "in vec2 vUv;",
    "uniform sampler2D uPrev;",
    "uniform sampler2D uThermal;",
    "uniform float uDecay;",
    "out vec4 oColor;",
    "void main(){",
    "  float prev = texture(uPrev, vUv).r;",
    "  float src = texture(uThermal, vUv).r;",
    "  float h = max(src, prev * uDecay);",
    "  oColor = vec4(h, 0.0, 0.0, 1.0);",
    "}",
  ].join("\n");

  var COMPOSITE_FRAG = [
    "#version 300 es",
    "precision highp float;",
    "in vec2 vUv;",
    "uniform sampler2D uScene;",
    "uniform sampler2D uBloom;",
    "uniform sampler2D uThermal;",
    "uniform sampler2D uNoise;",
    "uniform float uBloomStrength;",
    "uniform float uHeatHaze;",
    "uniform float uFrame;",
    "uniform float uReducedMotion;",
    "uniform float uVignette;",
    "uniform float uGrain;",
    "uniform vec2 uShake;",
    "out vec4 oColor;",
    "",
    "void main(){",
    "  vec2 uv = vUv + uShake;",
    "  float heat = texture(uThermal, uv).r;",
    "  vec2 haze = vec2(0.0);",
    "  if (uHeatHaze > 0.0 && uReducedMotion < 0.5 && heat > 0.2){",
    "    float t = uFrame * 0.15;",
    "    haze = vec2(",
    "      sin(uv.y * 40.0 + t) * heat,",
    "      cos(uv.x * 36.0 + t * 1.3) * heat",
    "    ) * uHeatHaze * 0.004;",
    "  }",
    "  vec3 scene = texture(uScene, uv + haze).rgb;",
    "  vec3 bloom = texture(uBloom, uv).rgb;",
    "  vec3 color = scene + bloom * uBloomStrength;",
    "",
    "  // Soft ACES-ish tone map",
    "  color = color * (2.51 * color + 0.03) / (color * (2.43 * color + 0.59) + 0.14);",
    "  color = clamp(color, 0.0, 1.0);",
    "",
    "  // Warm grade near heat",
    "  color = mix(color, color * vec3(1.08, 0.98, 0.9), clamp(heat * 0.35, 0.0, 0.35));",
    "",
    "  // Vignette",
    "  vec2 vc = vUv * 2.0 - 1.0;",
    "  float vig = 1.0 - dot(vc, vc) * uVignette;",
    "  color *= clamp(vig, 0.55, 1.0);",
    "",
    "  if (uGrain > 0.0 && uReducedMotion < 0.5){",
    "    float g = texture(uNoise, vUv).r - 0.5;",
    "    color += g * uGrain;",
    "  }",
    "",
    "  // Final light quantize to keep crisp sandbox feel",
    "  color = floor(color * 48.0 + 0.5) / 48.0;",
    "  oColor = vec4(clamp(color, 0.0, 1.0), 1.0);",
    "}",
  ].join("\n");

  var PRESENT_FRAG = [
    "#version 300 es",
    "precision highp float;",
    "in vec2 vUv;",
    "uniform sampler2D uTex;",
    "out vec4 oColor;",
    "void main(){",
    "  oColor = texture(uTex, vUv);",
    "}",
  ].join("\n");

  var FX_FRAG = [
    "#version 300 es",
    "precision highp float;",
    "in vec2 vUv;",
    "uniform sampler2D uScene;",
    "uniform sampler2D uFx;",
    "out vec4 oColor;",
    "void main(){",
    "  vec3 scene = texture(uScene, vUv).rgb;",
    "  vec4 fx = texture(uFx, vUv);",
    "  vec3 color = scene + fx.rgb;",
    "  oColor = vec4(clamp(color, 0.0, 1.0), 1.0);",
    "}",
  ].join("\n");

  var GrainfallShaders = {
    VERT: VERT,
    CELL_FRAG: CELL_FRAG,
    LIGHT_FRAG: LIGHT_FRAG,
    BLOOM_THRESH_FRAG: BLOOM_THRESH_FRAG,
    BLOOM_BLUR_FRAG: BLOOM_BLUR_FRAG,
    THERMAL_FRAG: THERMAL_FRAG,
    COMPOSITE_FRAG: COMPOSITE_FRAG,
    PRESENT_FRAG: PRESENT_FRAG,
    FX_FRAG: FX_FRAG,
  };

  root.GrainfallShaders = GrainfallShaders;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = GrainfallShaders;
  }
})(typeof window !== "undefined" ? window : globalThis);
